#!/bin/bash
sudo fai-mirror -v /srv/files/scratch/mirror # >log.txt 2>error.txt
sudo fai-cd -m /srv/files/scratch/mirror/ fai-cd.iso
echo "test ISO or break with <CTRL> C"
read
fai-kvm -Nu 3 cd fai-cd.iso 
