#!/bin/bash

apt-get install build-essential fakeroot
apt-get build-dep linux

ainsl -v /etc/apt/sources.list "deb-src http://deb.debian.org/debian buster main" 
ainsl -v /etc/apt/sources.list "deb-src http://deb.debian.org/debian buster-updates main" 
ainsl -v /etc/apt/sources.list "deb-src http://deb.debian.org/debian-security/ buster/updates main" 

# from the net!
# deb http://deb.debian.org/debian buster main
# deb-src http://deb.debian.org/debian buster main
# deb http://deb.debian.org/debian-security/ buster/updates main
# deb-src http://deb.debian.org/debian-security/ buster/updates main
# deb http://deb.debian.org/debian buster-updates main
# deb-src http://deb.debian.org/debian buster-updates main

apt update

apt-get source linux

# cd linux-version
