#!/bin/bash

apt-get install build-essential fakeroot
apt-get build-dep linux

echo "deb-src http://deb.debian.org/debian buster main" >> /etc/apt/sources.list
echo "deb-src http://deb.debian.org/debian buster-updates main" >> /etc/apt/sources.list
echo "deb http://deb.debian.org/debian-security/ buster/updates main" >> /etc/apt/sources.list

# from the net!
# deb http://deb.debian.org/debian buster main
# deb-src http://deb.debian.org/debian buster main
# deb http://deb.debian.org/debian-security/ buster/updates main
# deb-src http://deb.debian.org/debian-security/ buster/updates main
# deb http://deb.debian.org/debian buster-updates main
# deb-src http://deb.debian.org/debian buster-updates main

apt update

apt-get source linux

# cd linux-version
