#! /bin/bash

# create default pxelinux boot configuration
fai-chboot -o default

# create a template for booting the installation
fai-chboot -Iv -f verbose,sshd,createvt,menu -u nfs://faiserver/srv/fai/config buster.tmpl

# Since we do not know the MAC address, our DHCP cannot provide the hostname.
# Therefore we do explicitly set the hostname
fai-chboot -Iv -f verbose,sshd,createvt -u nfs://faiserver/srv/fai/config -k hostname=gnomehost gnomehost
fai-chboot -Iv -f verbose,sshd,createvt -u nfs://faiserver/srv/fai/config -k hostname=demohost demohost
for c in {01..10}; do
    fai-chboot -Iv -f verbose,sshd,createvt,menu -u nfs://faiserver/srv/fai/config -k hostname=client$c client$c
done

exit 0
