#! /bin/bash
set -x 
error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# a list of modules which are loaded at boot time
#    ainsl -a /etc/modules "^$module$"

fcopy -irv -m=root,root,0755 /usr/local/sbin
fcopy -irv -m=root,root,0755 /usr/local/bin

ifclass DHCPC && ainsl -s /etc/hosts "127.0.0.1 $HOSTNAME"

ifclass XORG || $ROOTCMD make-auto-login-console demo # nur wenn keine grafische Oberflaeche.

ifclass XORG || ainsl -a /home/demo/.bashrc "sleep 3"
ifclass XORG || ainsl -a /home/demo/.bashrc "get-fai-config-space.bash"
ifclass XORG || ainsl /home/demo/.bashrc "sudo config-fai-server"
ifclass XORG || ainsl /home/demo/.bashrc "mv .bashrc old.bashrc # /var/tmp?? "

exit $error
