#! /bin/bash
set -x 
error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# a list of modules which are loaded at boot time
#    ainsl -a /etc/modules "^$module$"

fcopy -irv -m=root,root,0755 /usr/local/sbin
fcopy -irv -m=root,root,0755 /usr/local/bin

ifclass DHCPC && ainsl -s /etc/hosts "127.0.0.1 $HOSTNAME"

$ROOTCMD make-auto-login-console # nur wenn keine grafische Oberflaeche?

exit $error
