#! /bin/bash
# set -x 
# must be done before user generates
error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# /etc/skel/ files z.B. .bashrc fuer z.b. demo user.
# The location of /etc/skel can be changed by editing the line that begins with SKEL= 
# in the configuration file /etc/default/useradd. By default this line says SKEL=/etc/skel. 

# ainsl -a /etc/default/useradd "SKEL=/usr/local/etc/skel.toor"
fcopy -irv -m=root,root,0755 /etc/skel
# fcopy -irv -m=root,root,0755 /usr/local/etc

exit $error

