#! /bin/bash

# (c) Thomas Lange, 2001-2017, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# add additional user account
if [ -n "$username" ]; then
    if ! $ROOTCMD getent passwd $username ; then
	$ROOTCMD adduser --disabled-login --gecos "$username user" $username
	ifclass LABOR && $ROOTCMD usermod -p "$USERPW" $username
	userdir=$($ROOTCMD getent passwd "$username" | cut -d: -f6 )

	for g in $groups; do
	    $ROOTCMD adduser $username $g
	done
    fi
fi
