#!/bin/bash
#echo "keyboard-configuration keyboard-configuration/modelcode string pc105" |debconf-set-selections 
#echo "keyboard-configuration keyboard-configuration/xkb-keymap select de" |debconf-set-selections 
#echo "keyboard-configuration keyboard-configuration/variant select Germany" |debconf-set-selections 
#echo "keyboard-configuration keyboard-configuration/model select Generic 105-key (Intl) PC" |debconf-set-selections 
#echo "keyboard-configuration keyboard-configuration/layoutcode string de" |debconf-set-selections 
#echo "keyboard-configuration keyboard-configuration/optionscode string ctrl:nocaps,terminate:ctrl_alt_bksp" |debconf-set-selections 
#
# dpkg-reconfigure keyboard-configuration # -f noninteractive
# debconf-get-selections | grep keyboard-configuration
# dpkg-reconfigure keyboard-configuration
# setupcon -v
# loadkeys de # leider fehlt die Datei.
#
# [ "$CONSOLEFONT" ] && setfont -v $CONSOLEFONT
#
# nothing to do if $KEYMAP is undefined
# [ "$KEYMAP" ] || exit
#
echo 'XKBMODEL="pc105"' >/etc/default/keyboard
echo 'XKBLAYOUT="de"' >>/etc/default/keyboard
echo 'XKBVARIANT=""' >>/etc/default/keyboard
echo 'XKBOPTIONS=""' >>/etc/default/keyboard

echo -n "Loading keymap(s) $KEYMAP ..."
# if [ -x /bin/setupcon ]; then
#    layout=$(echo $KEYMAP|cut -d - -f 1)
#    variant=$(echo $KEYMAP|cut -d - -f 3)
#    sed -e "s#^XKBLAYOUT=.*#XKBLAYOUT=\"$layout\"#" \
#        -e "s#^XKBVARIANT=.*#XKBVARIANT=\"$variant\"#" \
cat /etc/default/keyboard > /.console-setup
setupcon -k --force
echo "done."
# else
#    loadkeys -q $KEYMAP && echo "done."
#fi
