#!/bin/bash
export LANG=C
sudo sed -i -e 's:^#  AutomaticLoginEnable = true:AutomaticLoginEnable = true:' $target/etc/gdm3/daemon.conf
sudo sed -i -e 's:^#  AutomaticLogin = user1:AutomaticLogin = demo:' $target/etc/gdm3/daemon.conf

