#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# set root password
if [ -n "$ROOTPW" ]; then
    $ROOTCMD usermod -p "$ROOTPW" root
else
    $ROOTCMD usermod -L root
fi

# echo 'demo ALL=(ALL:ALL) NOPASSWD:ALL' > $target/etc/sudoers.d/gen4testing
# chmod 0440 $target/etc/sudoers.d/gen4testing

exit $error

